<?xml version="1.0" encoding="utf-8"?><Database Name="Tfour" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DANLE14E0\SQLEXPRESS;Initial Catalog=Tfour;Integrated Security=True" SettingsObjectName="Tfour_Main.Properties.Settings" SettingsPropertyName="TfourConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PlayerInformation" Member="PlayerInformations">
    <Type Name="PlayerInformation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>